// dashboard.js — Life OS Dashboard v1
// Smart Reports: stored in smart_reports table, generated by Claude on schedule
import { supabase } from './supabase.js';
import { today } from './utils.js?v=2';

const T = today(); // PST today's date

const DOW_NAMES  = ['sun','mon','tue','wed','thu','fri','sat'];
const DOW_LABELS = { sun:'Dom', mon:'Lun', tue:'Mar', wed:'Mié', thu:'Jue', fri:'Vie', sat:'Sáb' };

function esc(s) {
  return String(s || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}

function fmtDateTime(iso) {
  if (!iso) return '';
  const d = new Date(iso);
  const now = new Date();
  const diffMs = now - d;
  const diffHrs = diffMs / 3600000;
  if (diffHrs < 1) return 'Hace unos minutos';
  if (diffHrs < 24) return `Hace ${Math.floor(diffHrs)}h`;
  const diffDays = Math.floor(diffMs / 86400000);
  if (diffDays === 1) return 'Ayer';
  if (diffDays < 7) return `Hace ${diffDays} días`;
  return d.toLocaleDateString('es', { month: 'short', day: 'numeric' });
}

function getScheduleLabel(r) {
  if (r.frequency === 'daily') return 'Cada día';
  if (r.frequency === 'weekly') {
    const dow = r.day_of_week ? (DOW_LABELS[r.day_of_week] || r.day_of_week) : '?';
    return `Cada ${dow}`;
  }
  if (r.frequency === 'monthly') return `Día ${r.day_of_month || '?'} de cada mes`;
  return r.frequency;
}

function getFreqIcon(freq) {
  if (freq === 'daily')   return '📅';
  if (freq === 'weekly')  return '📆';
  if (freq === 'monthly') return '🗓️';
  return '📊';
}

function isDue(r) {
  if (!r.next_run_date) return true; // never run = always due
  if (r.force_update)  return true; // manually requested
  return r.next_run_date <= T;
}

// ── Load & Render ─────────────────────────────────────────────────────────────
let allReports = [];

async function load() {
  const { data, error } = await supabase
    .from('smart_reports')
    .select('*')
    .eq('active', true)
    .order('sort_order', { ascending: true })
    .order('created_at', { ascending: true });

  if (error) { console.error('load error', error); return; }
  allReports = data || [];

  const daily   = allReports.filter(r => r.frequency === 'daily');
  const weekly  = allReports.filter(r => r.frequency === 'weekly');
  const monthly = allReports.filter(r => r.frequency === 'monthly');

  renderSection('daily',   daily);
  renderSection('weekly',  weekly);
  renderSection('monthly', monthly);

  // Due count badge
  const dueCount = allReports.filter(r => isDue(r)).length;
  const badge = document.getElementById('dash-due-count');
  if (badge) {
    if (dueCount > 0) {
      badge.style.display = '';
      badge.textContent = `${dueCount} pendiente${dueCount > 1 ? 's' : ''}`;
    } else {
      badge.style.display = 'none';
    }
  }

  const subtitle = document.getElementById('dash-subtitle');
  if (subtitle) {
    const total = allReports.length;
    subtitle.textContent = total === 0
      ? 'Agrega Smart Reports abajo'
      : `${total} reporte${total !== 1 ? 's' : ''} · ${dueCount > 0 ? dueCount + ' pendiente' + (dueCount > 1 ? 's' : '') : 'al día'}`;
  }
}

function renderSection(freq, reports) {
  const el = document.getElementById(`sr-${freq}-list`);
  if (!el) return;
  if (!reports.length) {
    const labels = { daily: 'diarios', weekly: 'semanales', monthly: 'mensuales' };
    el.innerHTML = `<div class="sr-empty">Sin reportes ${labels[freq] || ''}. Agrega uno arriba.</div>`;
    return;
  }
  el.innerHTML = reports.map(r => reportCardHtml(r)).join('');
}

function reportCardHtml(r) {
  const due = isDue(r);
  const icon = getFreqIcon(r.frequency);
  const schedLabel = getScheduleLabel(r);
  const updatedAgo = r.response_updated_at ? fmtDateTime(r.response_updated_at) : null;

  let dueBadge = '';
  if (!r.response) {
    dueBadge = `<span class="sr-due-badge">⏳ Sin respuesta</span>`;
  } else if (due) {
    dueBadge = `<span class="sr-due-badge overdue">🔄 Actualización pendiente</span>`;
  } else {
    dueBadge = `<span class="sr-due-badge fresh">✅ Al día</span>`;
  }

  // Force-update toggle: shows whether update is requested (auto-due OR manually forced)
  const autoScheduleDue = !r.next_run_date || r.next_run_date <= T;
  const isForced = !!r.force_update;
  const isActive  = autoScheduleDue || isForced;
  const toggleTitle = isForced && !autoScheduleDue
    ? 'Cancelar solicitud de actualización anticipada'
    : autoScheduleDue
    ? 'Actualización programada automáticamente'
    : 'Solicitar actualización anticipada';
  const toggleClass = isActive ? 'sr-force-btn active' : 'sr-force-btn';
  const toggleIcon  = isActive ? '🔔' : '🔕';

  const responseSection = r.response
    ? `<div class="sr-response-text">${esc(r.response).replace(/\n/g, '<br>')}</div>
       ${updatedAgo ? `<div class="sr-response-date">Actualizado ${updatedAgo}</div>` : ''}`
    : `<div class="sr-response-empty">Sin respuesta aún — Claude generará este reporte la próxima vez que trabajes en LifeOS.</div>`;

  return `
    <div class="sr-card" id="sr-card-${r.id}">
      <div class="sr-card-header" onclick="toggleSrCard('${r.id}')">
        <div class="sr-card-left">
          <div class="sr-card-icon">${icon}</div>
          <div style="min-width:0">
            <div class="sr-card-title">${esc(r.title)}</div>
            <div class="sr-card-meta" style="display:flex;align-items:center;gap:6px;margin-top:3px;flex-wrap:wrap">${schedLabel} &nbsp;${dueBadge}</div>
          </div>
        </div>
        <div class="sr-card-actions" onclick="event.stopPropagation()">
          <button class="${toggleClass}" onclick="toggleSrForceUpdate('${r.id}')" title="${toggleTitle}">${toggleIcon}</button>
          <button class="sr-action-btn" onclick="editSrReport('${r.id}')" title="Editar">✏️</button>
          <button class="sr-action-btn" onclick="deleteSrReport('${r.id}')" title="Eliminar" style="color:var(--coral,#e8563a)">🗑️</button>
        </div>
      </div>
      <div class="sr-card-divider"></div>
      <div class="sr-card-response">
        ${responseSection}
        <div class="sr-prompt-label">Prompt de Claude</div>
        <div class="sr-prompt-text">${esc(r.prompt)}</div>
      </div>
    </div>`;
}

window.toggleSrCard = function(id) {
  const card = document.getElementById(`sr-card-${id}`);
  if (card) card.classList.toggle('expanded');
};

window.toggleSrForceUpdate = async function(id) {
  const r = allReports.find(x => x.id === id);
  if (!r) return;

  const autoScheduleDue = !r.next_run_date || r.next_run_date <= T;

  // If auto-scheduled due, the bell is already on — toggling manually cycles:
  //   auto-due + not forced → set force_update true (belt-and-suspenders, visual confirmation)
  //   force_update true     → clear it (only affects manual override, auto-due stays)
  // If not auto-due:
  //   not forced → turn on (request early update)
  //   forced     → turn off (cancel early request)
  const newVal = !r.force_update;

  const { error } = await supabase
    .from('smart_reports')
    .update({ force_update: newVal })
    .eq('id', id);

  if (error) { console.error('toggleSrForceUpdate error', error); return; }

  r.force_update = newVal;
  await load();
};

// ── Modal state ───────────────────────────────────────────────────────────────
let _srFreq   = 'daily';
let _srDow    = null;
let _srDom    = 1;
let _srEditId = null;

window.showAddReport = function(freq) {
  _srEditId = null;
  _srFreq   = freq || 'daily';
  _srDow    = null;
  _srDom    = 1;

  document.getElementById('sr-title').value  = '';
  document.getElementById('sr-prompt').value = '';
  document.getElementById('sr-dom').value    = '1';

  document.querySelectorAll('#sr-freq-pills .freq-pill').forEach(b => b.classList.remove('selected'));
  const fp = document.querySelector(`#sr-freq-pills [data-freq="${_srFreq}"]`);
  if (fp) fp.classList.add('selected');

  document.querySelectorAll('#sr-dow-grid .dow-btn').forEach(b => b.classList.remove('selected'));

  _updateSrSections();

  document.getElementById('sr-modal-title').textContent = '📊 Nuevo Smart Report';
  document.getElementById('sr-submit-btn').textContent  = 'Guardar reporte';
  document.getElementById('sr-modal').style.display     = 'flex';
  setTimeout(() => document.getElementById('sr-title').focus(), 50);
};

window.closeSrModal = function() {
  document.getElementById('sr-modal').style.display = 'none';
  _srEditId = null;
};

window.pickSrFreq = function(btn) {
  document.querySelectorAll('#sr-freq-pills .freq-pill').forEach(b => b.classList.remove('selected'));
  btn.classList.add('selected');
  _srFreq = btn.dataset.freq;
  _updateSrSections();
};

window.pickSrDow = function(btn) {
  document.querySelectorAll('#sr-dow-grid .dow-btn').forEach(b => b.classList.remove('selected'));
  btn.classList.add('selected');
  _srDow = btn.dataset.dow;
};

function _updateSrSections() {
  document.getElementById('sr-dow-section').style.display = _srFreq === 'weekly'  ? '' : 'none';
  document.getElementById('sr-dom-section').style.display = _srFreq === 'monthly' ? '' : 'none';
}

window.editSrReport = async function(id) {
  const r = allReports.find(x => x.id === id);
  if (!r) return;

  _srEditId = id;
  _srFreq   = r.frequency;
  _srDow    = r.day_of_week   || null;
  _srDom    = r.day_of_month  || 1;

  document.getElementById('sr-title').value  = r.title  || '';
  document.getElementById('sr-prompt').value = r.prompt || '';
  document.getElementById('sr-dom').value    = String(_srDom);

  document.querySelectorAll('#sr-freq-pills .freq-pill').forEach(b => b.classList.remove('selected'));
  const fp = document.querySelector(`#sr-freq-pills [data-freq="${_srFreq}"]`);
  if (fp) fp.classList.add('selected');

  document.querySelectorAll('#sr-dow-grid .dow-btn').forEach(b => {
    b.classList.toggle('selected', b.dataset.dow === _srDow);
  });

  _updateSrSections();

  document.getElementById('sr-modal-title').textContent = '✏️ Editar Smart Report';
  document.getElementById('sr-submit-btn').textContent  = 'Guardar cambios';
  document.getElementById('sr-modal').style.display     = 'flex';
  setTimeout(() => document.getElementById('sr-title').focus(), 50);
};

window.submitSrReport = async function() {
  const title  = document.getElementById('sr-title').value.trim();
  const prompt = document.getElementById('sr-prompt').value.trim();
  if (!title)  { alert('Escribe un título'); return; }
  if (!prompt) { alert('Escribe el prompt'); return; }
  if (_srFreq === 'weekly' && !_srDow) { alert('Selecciona el día de la semana'); return; }

  const domVal = Number(document.getElementById('sr-dom').value) || 1;

  const payload = {
    title,
    prompt,
    frequency:    _srFreq,
    day_of_week:  _srFreq === 'weekly'  ? _srDow  : null,
    day_of_month: _srFreq === 'monthly' ? domVal  : null,
  };

  let error;
  if (_srEditId) {
    ({ error } = await supabase.from('smart_reports').update(payload).eq('id', _srEditId));
  } else {
    // next_run_date = null means it's always due → Claude will generate it on next session
    ({ error } = await supabase.from('smart_reports').insert({ ...payload, next_run_date: null }));
  }

  if (error) { alert('Error: ' + error.message); return; }
  closeSrModal();
  await load();
};

window.deleteSrReport = async function(id) {
  if (!confirm('¿Eliminar este Smart Report?')) return;
  const { error } = await supabase.from('smart_reports').delete().eq('id', id);
  if (error) { alert('Error: ' + error.message); return; }
  await load();
};

// ── Today's Tasks ────────────────────────────────────────────────────────────
async function loadTodayTasks() {
  const el = document.getElementById('today-tasks-list');
  if (!el) return;

  const { data, error } = await supabase
    .from('tasks')
    .select('id, title, module, priority, status')
    .eq('due_date', T)
    .neq('status', 'done')
    .order('priority', { ascending: false })
    .order('created_at', { ascending: true });

  if (error) { el.innerHTML = `<div class="sr-empty">Error cargando tareas</div>`; return; }

  if (!data || data.length === 0) {
    el.innerHTML = `<div class="sr-empty">Sin tareas para hoy. ¡Excelente!</div>`;
    return;
  }

  const moduleIcon = { RT:'🏫', TOV:'💍', Personal:'👤', Health:'🏃', LifeOS:'🖥️' };
  const prioColor  = { urgent: 'urgent', high: 'urgent', normal: 'normal', low: 'normal' };

  el.innerHTML = data.map(t => `
    <div class="dash-task-item">
      <div class="dash-task-dot ${prioColor[t.priority] || 'normal'}"></div>
      <span>${esc(t.title)}</span>
      <span class="dash-task-module">${moduleIcon[t.module] || ''} ${esc(t.module || '')}</span>
    </div>`).join('');
}

// ── Today's Food Log ──────────────────────────────────────────────────────────
async function loadTodayFood() {
  const el = document.getElementById('today-food-list');
  if (!el) return;

  const { data, error } = await supabase
    .from('food_log')
    .select('id, meal, description, notes')
    .eq('date', T)
    .order('id', { ascending: true });

  if (error) { el.innerHTML = `<div class="sr-empty">Error cargando comidas</div>`; return; }

  if (!data || data.length === 0) {
    el.innerHTML = `<div class="sr-empty">Sin comidas registradas hoy.</div>`;
    return;
  }

  const mealEmoji = { Breakfast:'🌅', Lunch:'☀️', Dinner:'🌙', Snack:'🍎', Other:'🍽️' };
  el.innerHTML = data.map(f => `
    <div class="dash-food-item">
      <div class="dash-food-meal">${mealEmoji[f.meal] || '🍽️'} ${esc(f.meal)}</div>
      <div class="dash-food-desc">${esc(f.description)}${f.notes ? `<div style="font-size:11px;color:var(--gray-400);margin-top:2px">${esc(f.notes)}</div>` : ''}</div>
    </div>`).join('');
}

// ── Quick Food Log ────────────────────────────────────────────────────────────
window.logFoodFromDash = async function() {
  const meal  = document.getElementById('fq-meal')?.value;
  const desc  = document.getElementById('fq-desc')?.value?.trim();
  if (!desc) { document.getElementById('fq-desc')?.focus(); return; }

  const btn = document.querySelector('.food-quick-btn');
  if (btn) { btn.disabled = true; btn.textContent = '…'; }

  const { error } = await supabase.from('food_log').insert({
    date: T,
    meal,
    description: desc,
    notes: null,
  });

  if (btn) { btn.disabled = false; btn.textContent = '+'; }

  if (error) { console.error('logFoodFromDash error', error); return; }

  // Clear input and reload food list
  document.getElementById('fq-desc').value = '';
  await loadTodayFood();
};

// Also allow pressing Enter in the description input
document.addEventListener('DOMContentLoaded', () => {
  const input = document.getElementById('fq-desc');
  if (input) input.addEventListener('keydown', e => { if (e.key === 'Enter') window.logFoodFromDash(); });
});

// ── Init ──────────────────────────────────────────────────────────────────────
load();
loadTodayTasks();
loadTodayFood();
